// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppTopBar: typeof import('./src/components/AppTopBar.vue')['default']
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    BrandLogo: typeof import('./src/components/images/BrandLogo.vue')['default']
    Example: typeof import('./src/components/Example.vue')['default']
    ICarbonLogout: typeof import('~icons/carbon/logout')['default']
    ICarbonMenu: typeof import('~icons/carbon/menu')['default']
    ICarbonMoon: typeof import('~icons/carbon/moon')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
    IMdiFacebook: typeof import('~icons/mdi/facebook')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiGoogle: typeof import('~icons/mdi/google')['default']
    IMdiTwitter: typeof import('~icons/mdi/twitter')['default']
    ISimpleIconsSupabase: typeof import('~icons/simple-icons/supabase')['default']
    ISimpleIconsVuedotjs: typeof import('~icons/simple-icons/vuedotjs')['default']
    LoadingIcon: typeof import('./src/components/LoadingIcon.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NavDrawer: typeof import('./src/components/NavDrawer.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    PromoteSection: typeof import('./src/components/PromoteSection.vue')['default']
    VButton: typeof import('./src/components/VButton.vue')['default']
    VIconButton: typeof import('./src/components/VIconButton.vue')['default']
    VInput: typeof import('./src/components/VInput.vue')['default']
    VLabel: typeof import('./src/components/VLabel.vue')['default']
    VPasswordInput: typeof import('./src/components/VPasswordInput.vue')['default']
  }
}

export { }
